### ISSUE TITLE
Cant deobfuscate

### ISSUE THREAD

**Issue by zangxx66** [mindedsecurity/JStillery#22]
js error:deobfuscate is not defined

**Comment by realtebo** [comment]
Same problem here:

```
Uncaught ReferenceError: deobfuscate is not defined
    at Object.<anonymous> (jstillery.jQuery.js:247)
    at j (jquery-1.11.2.min.js:2)
    at Object.fireWith [as rejectWith] (jquery-1.11.2.min.js:2)
    at x (jquery-1.11.2.min.js:4)
    at XMLHttpRequest.b (jquery-1.11.2.min.js:4)
```

**Comment by realtebo** [comment]
It's due to an error of loading 

```
http://localhost:3001/static/js/jstiller.browser.js

Cannot GET /static/js/jstiller.browser.js

```

This fill doesn't exists !

**Comment by realtebo** [comment]
Esit of obfuscation via cli on the same file

```
$ ./jstillery_cli.js ./mine.min.js
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
unknown expression type: undefined
[EE] Error: Should not happen
    at findPropFromAST (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:326:23)
    at resolveMemberExpression (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:568:17)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:2342:19)
    at ast_reduce_scoped (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:841:14)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:1131:18)
    at ast_reduce_scoped (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:841:14)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:2980:22)
    at ast_reduce_scoped (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:841:14)
    at Array.map (<anonymous>)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:3049:40) Error: Should not happen
    at findPropFromAST (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:326:23)
    at resolveMemberExpression (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:568:17)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:2342:19)
    at ast_reduce_scoped (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:841:14)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:1131:18)
    at ast_reduce_scoped (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:841:14)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:2980:22)
    at ast_reduce_scoped (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:841:14)
    at Array.map (<anonymous>)
    at ast_reduce (C:\Users\mirko\Desktop\jstillery\JStillery\src\jstiller.js:3049:40) { type: 'Property',
  key: { type: 'Identifier', name: 'F7' },
  value:
   { type: 'MemberExpression',
     computed: false,
     object:
      Identifier { type: 'Identifier', name: 'M8k', loc: [Object], firstObj: true },
     property:
      Identifier {
        type: 'Identifier',
        name: 'Z7B',
        loc: [Object],
        parent: [Circular] } } } { type: 'ObjectExpression',
  properties:
   [ { type: 'Property', key: [Object], value: [Object] },
     { type: 'Property', key: [Object], value: [Object] },
     { type: 'Property', key: [Object], value: [Object] },
     { type: 'Property', key: [Object], value: [Object] } ] } [ 'A7', 'I7' ]
```

**Comment by wisec** [comment]
Hey @zangxx66 , 
thanks for reporting this, the build script has indeed a bug which prevents the server to find the browserified version of JStillery.
Fix will arrive soon

**Comment by wisec** [comment]
First build then launch the server:
npm run build_server && npm run start_server

Closing it
